skills_analysis:
  description: "Research and analyze job posting to extract required and preferred skills along with experience and education insights"
  expected_output: "Structured analysis of required skills, preferred skills, experience level, education requirements, and all technical skills mentioned"
  agent: researcher_agent

compensation_analysis:
  description: "Evaluate salary range, listed benefits, and provide market compensation insights"
  expected_output: "Comprehensive salary analysis and benefits breakdown with negotiation guidance"
  agent: negotiator_agent

quality_assessment:
  description: "Assess job posting quality, completeness, and identify potential red flags or positive indicators"
  expected_output: "Job quality score, completeness rating, identified red flags, and green flags with risk assessment"
  agent: skeptic_agent