linkedin_job_search_task:
  description: >
    Search LinkedIn for job opportunities matching the specified criteria for {{search_criteria}}.
    Use the LinkedIn MCP tool 'search_jobs' to find relevant positions based on the provided parameters.
    Return structured job data suitable for database persistence and analysis.
    
    Focus on retrieving complete job information including:
    - Job title and company details
    - Location and remote work options
    - Job URLs for direct application
    - Job descriptions and requirements
    - Date posted and other metadata

  expected_output: >
    JSON object with job search results for database persistence:
    {
      "type": "object",
      "properties": {
        "search_summary": {"type": "string"},
        "consolidated_jobs": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "title": {"type": "string"},
              "company": {"type": "string"},
              "location": {"type": "string"},
              "job_url": {"type": "string"},
              "job_url_direct": {"type": "string"},
              "description": {"type": "string"},
              "job_type": {"type": "string"},
              "date_posted": {"type": "string"},
              "site": {"type": "string"},
              "is_remote": {"type": "boolean"},
              "experience_level": {"type": "string"}
            }
          }
        },
        "total_jobs": {"type": "integer"},
        "success": {"type": "boolean"}
      },
      "required": [
        "search_summary",
        "consolidated_jobs",
        "total_jobs",
        "success"
      ]
    }
  # Field names must match the schema exactly for database persistence.

  agent: linkedin_job_searcher

job_opportunity_analysis_task:
  description: >
    Analyze the top LinkedIn job opportunities identified in the search for {{search_criteria}}.
    For each opportunity, evaluate:
    - Job requirements alignment with user profile
    - Company reputation and growth potential
    - Role progression and career development opportunities
    - Compensation competitiveness (when available)
    - Cultural fit indicators from job posting and company page
    Provide actionable insights about pursuit priority and application strategy.

  expected_output: >
    JSON object matching schema:
    {
      "type": "object",
      "properties": {
        "analyzed_opportunities": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "job_title": {"type": "string"},
              "company_name": {"type": "string"},
              "fit_score": {"type": "integer"},
              "pros": {"type": "array", "items": {"type": "string"}},
              "cons": {"type": "array", "items": {"type": "string"}},
              "application_priority": {"type": "string"},
              "key_requirements": {"type": "array", "items": {"type": "string"}},
              "growth_potential": {"type": "string"}
            }
          }
        },
        "overall_market_insights": {"type": "array", "items": {"type": "string"}}
      },
      "required": [
        "analyzed_opportunities",
        "overall_market_insights"
      ]
    }
  # Field names must match the schema exactly.

  agent: job_opportunity_analyzer
  context: [linkedin_job_search_task]



linkedin_report_compilation_task:
  description: >
    Compile a focused LinkedIn job search report for {{search_criteria}} that consolidates
    the job search results and opportunity analyses into actionable job recommendations.
    Focus on providing a clean summary of found opportunities with key insights and
    next steps for job applications. This is a simplified report focused on job discovery
    rather than networking strategies.

  expected_output: >
    JSON object matching schema:
    {
      "type": "object",
      "properties": {
        "executive_summary": {"type": "string"},
        "priority_opportunities": {
          "type": "array",
          "items": {
            "type": "object", 
            "properties": {
              "rank": {"type": "integer"},
              "job_title": {"type": "string"},
              "company_name": {"type": "string"},
              "rationale": {"type": "string"},
              "next_steps": {"type": "array", "items": {"type": "string"}}
            }
          }
        },
        "application_recommendations": {"type": "array", "items": {"type": "string"}},
        "market_insights": {"type": "array", "items": {"type": "string"}}
      },
      "required": [
        "executive_summary",
        "priority_opportunities", 
        "application_recommendations",
        "market_insights"
      ]
    }
  # Field names must match the schema exactly.

  agent: linkedin_report_writer
  context: [linkedin_job_search_task, job_opportunity_analysis_task]