research_strategy_task:
  description: >
    Develop and execute a research strategy for {{company_name}}.
    Break down the work into independent subtasks, each delegated to the correct agent:
      - Financial Analyst → financial health, funding history, investors, revenue
      - Culture Investigator → workplace culture, employee reviews, merger impacts
      - Leadership Analyst → leadership reputation, management style, credibility
      - Career Growth Researcher → advancement opportunities, roles, training, promotions
      - News Analyst → recent press releases, acquisitions, partnerships, major events

    Each delegated task should produce a JSON field with the subtopic as the key.

    After delegating and collecting results, synthesize them into a structured
    company research report.

  expected_output: >
    A consolidated JSON object with the following structure:
    {
      "company_name": "...",
      "financial_health": "...",
      "workplace_culture": "...",
      "leadership_reputation": "...",
      "career_growth": "...",
      "recent_news": "...",
      "overall_summary": "..."
    }

  agent: research_manager