# 8. Final report writing
final_report_task:
  description: >
    Transform the synthesized research into a JSON-formatted report designed for job seekers.
    The JSON should include these sections:
      - company_name
      - financial_health
      - workplace_culture
      - leadership_reputation
      - career_growth
      - recent_news
      - overall_summary
    Make sure the JSON is valid and strictly follows the schema.
    Delegate work to coworker mcp_researcher when you need fresh web details.
  expected_output: >
    A valid JSON object containing the research findings in the specified schema.
    Your final answer MUST be valid JSON.
  agent: report_writer
  output_file: "company_report.json"
