financial_analysis_task:
  description: >
    Provide a quick financial snapshot of {{company_name}}. 
    Focus only on major signals that could impact candidate fit, 
    such as recent funding events, major investors, or clear signs of growth or instability.
    Avoid detailed analysis — the goal is just to flag any important financial context.

  expected_output: >
    A short JSON object:
    {
      "funding_events": "latest round if any, else 'none found'",
      "notable_investors": ["top 1-2 investors if known"],
      "financial_trend": "growing | stable | declining (based on quick scan)",
      "risk_flag": "yes/no with 1 sentence reason"
    }

  agent: financial_analyst
  #context: [web_research_task]

culture_investigation_task:
  description: >
    Provide a quick cultural snapshot of {{company_name}}. 
    Identify the official company values or mission statement from {{company_name}}'s website 
    (or LinkedIn/Glassdoor if not available). 
    Supplement this with recent employee sentiment and major cultural signals. 
    Keep it lightweight — the goal is to quickly gauge cultural alignment, not a full HR report.

  expected_output: >
    A short JSON object:
    {
      "company_values": ["list the official values or mission points if published"],
      "employee_sentiment": "positive | mixed | negative (with 1-sentence context)",
      "work_life_balance": "strong | average | weak (with 1-sentence context)",
      "culture_signals": ["up to 3 quick highlights"],
      "risk_flag": "yes/no with 1 sentence reason"
    }

  agent: culture_investigator
  #context: [web_research_task]

leadership_analysis_task:
  description: >
    Provide a quick snapshot of {{company_name}}'s leadership. 
    Identify key executives (CEO, top leaders), recent leadership changes or news, 
    and overall reputation signals from media or employee feedback. 
    Keep this lightweight — the goal is to flag major leadership strengths or risks, 
    not to provide a full executive dossier.

  expected_output: >
    A short JSON object:
    {
      "executive_team": ["CEO + top 2-3 leaders with roles"],
      "recent_news": "1-2 sentence summary of notable leadership news/changes",
      "leadership_reputation": "positive | mixed | negative (with 1-sentence context)",
      "leadership_strengths": ["up to 3 quick strengths"],
      "reputation_risks": ["up to 3 quick risks"]
    }

  agent: leadership_analyst
  #context: [web_research_task]

career_growth_analysis_task:
  description: >
    Provide a quick snapshot of career development opportunities at {{company_name}}. 
    Look for signals in official company materials (careers page, job postings) and 
    employee feedback (reviews, testimonials). 
    Focus on whether growth opportunities exist, how training/mentorship is described, 
    and whether employees perceive advancement as accessible. 
    Keep this lightweight — the goal is to flag career growth signals, not a full HR analysis.

  expected_output: >
    A short JSON object:
    {
      "advancement_opportunities": "1-2 sentence summary from careers site or reviews",
      "training_support": "brief note on training/mentorship if available",
      "employee_sentiment": "positive | mixed | negative (with 1-sentence context)",
      "growth_signals": ["up to 3 quick highlights"],
      "growth_risks": ["up to 3 quick risks"]
    }

  agent: career_growth_analyst
  #context: [web_research_task]

web_research_task:
  description: >
    Conduct comprehensive web research for {{company_name}} to gather the latest
    information including recent news, press releases, acquisitions, partnerships,
    major events, and any other current developments. Focus on information that
    would be relevant for job seekers and recent changes that might affect the
    company's outlook.
    
  expected_output: >
    A JSON object with recent web research findings:
    {
      "recent_news": {
        "latest_developments": "...",
        "press_releases": "...",
        "acquisitions_partnerships": "...",
        "major_events": "...",
        "market_changes": "...",
        "recent_announcements": "...",
        "news_summary": "...",
        "key_updates": ["..."]
      }
    }
    
  agent: mcp_researcher

report_compilation_task:
  description: >
    Compile and synthesize all research findings about {{company_name}} into a 
    comprehensive, job seeker-friendly company profile. Integrate insights from 
    financial analysis, culture investigation, leadership analysis, career growth 
    research, and recent news into a cohesive report with an overall assessment.
    
  expected_output: >
    A complete JSON report with all research findings:
    {
      "company_name": "{{company_name}}",
      "financial_health": {}, 
      "workplace_culture": {},
      "leadership_reputation": {},
      "career_growth": {},
      "overall_summary": {
        "recommendation_score": "...",
        "key_strengths": ["..."],
        "potential_concerns": ["..."],
        "best_fit_for": "...",
        "summary": "..."
      }
    }
    
  agent: report_writer
  context: [financial_analysis_task, culture_investigation_task, leadership_analysis_task, career_growth_analysis_task] #, web_research_task]