# 8. Final report writing
final_report_task:
  description: >
    Summarize the research into a JSON report with sections:
      - company_name
      - financial_health
      - workplace_culture
      - leadership_reputation
      - career_growth
      - recent_news
      - overall_summary
    Ensure the JSON is valid and follows the schema.
  expected_output: >
    A valid JSON object containing the research findings in the specified schema.
    Your final answer MUST be valid JSON.
  agent: report_writer
  output_file: "company_report.json"
