# 1. Research strategy planning
research_strategy_task:
  description: >
    Break down the research request into a strategy for investigating the target company.
    Identify what information is needed across financials, culture, leadership, growth, 
    and recent news. Delegate tasks to the appropriate specialist agents.
  expected_output: >
    A structured outline of research tasks to be completed by the analysts.
  agent: research_manager

# 2. Fresh news and updates (DuckDuckGo via MCP)
latest_news_task:
  description: >
    Use DuckDuckGo to find the 5 most recent and relevant news items about {company_name}.
    Focus on things that would matter to a job seeker such as layoffs, funding, leadership changes, 
    major controversies, or awards.
  expected_output: >
    A list of 5 news items with title, date, source, and summary.
  agent: mcp_researcher

# 3. Financial analysis
financial_analysis_task:
  description: >
    Analyze the financial health of {company_name}. Check for indicators of stability or risk, 
    such as recent funding, profitability, layoffs, or rapid expansion.
    Explain what these signals mean for a potential employee.
  expected_output: >
    A clear analysis of financial stability with 2-3 key metrics or events, and a plain-language
    explanation of what it means for job seekers.
  context: [latest_news_task]
  agent: financial_analyst

# 4. Workplace culture analysis
culture_analysis_task:
  description: >
    Research the workplace culture of {company_name}. Use employee reviews, 
    workplace reputation, diversity and inclusion practices, and employee satisfaction indicators. 
    Highlight strengths and weaknesses that matter to job seekers.
  expected_output: >
    A summary of workplace culture including 2-3 positive aspects and 2-3 potential red flags.
  context: [latest_news_task]
  agent: culture_investigator

# 5. Leadership and reputation analysis
leadership_analysis_task:
  description: >
    Research the leadership team at {company_name}. Identify CEO and senior leadership reputation, 
    management style, and any notable controversies or praise in the media. 
    Explain how leadership perception might affect job seekers.
  expected_output: >
    A profile of leadership reputation with key highlights (positive and negative)
    and a summary of how they impact workplace perception.
  context: [latest_news_task]
  agent: leadership_analyst

# 6. Career growth opportunities
career_growth_task:
  description: >
    Investigate career development and growth opportunities at {company_name}. 
    Look into internal mobility, employee advancement, mentorship programs, training support, 
    and job posting patterns.
  expected_output: >
    A summary of career growth opportunities with 2-3 examples of how employees
    can progress at this company.
  context: [latest_news_task]
  agent: career_growth_analyst

# 7. Synthesis task (manager)
synthesis_task:
  description: >
    Collect and integrate the findings from all research tasks (financial, culture, leadership, 
    career growth, and news). Ensure the information is cross-checked, consistent, 
    and structured for report writing.
  expected_output: >
    A consolidated research summary organized by category, ready to be turned into a structured report.
  context: [latest_news_task]
  agent: research_manager

# 8. Final report writing
final_report_task:
  description: >
    Transform the synthesized research into a JSON-formatted report designed for job seekers.
    The JSON should include these sections:
      - company_name
      - financial_health
      - workplace_culture
      - leadership_reputation
      - career_growth
      - recent_news
      - overall_summary
    Make sure the JSON is valid and strictly follows the schema.
  expected_output: >
    A valid JSON object containing the research findings in the specified schema.
    Your final answer MUST be valid JSON.
  context: [latest_news_task]
  agent: report_writer
  output_file: "company_report.json"
