fetch_recommended_jobs:
  description: >
    Fetch personalized job recommendations from LinkedIn using the 'get_recommended_jobs' MCP tool.
    This tool retrieves jobs that LinkedIn's algorithm recommends based on the user's profile,
    activity, and job preferences. Return structured job data suitable for database persistence.
    
    Focus on retrieving complete job information including:
    - Job title and company details  
    - Location and remote work options
    - Job URLs for direct application
    - Job descriptions and requirements
    - Date posted and recommendation metadata

  expected_output: >
    JSON object with recommended job results for database persistence:
    {
      "type": "object",
      "properties": {
        "recommendation_summary": {"type": "string"},
        "recommended_jobs": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "title": {"type": "string"},
              "company": {"type": "string"},
              "location": {"type": "string"},
              "job_url": {"type": "string"},
              "job_url_direct": {"type": "string"},
              "description": {"type": "string"},
              "job_type": {"type": "string"},
              "date_posted": {"type": "string"},
              "site": {"type": "string"},
              "is_remote": {"type": "boolean"},
              "recommendation_score": {"type": "number"},
              "recommendation_reasons": {"type": "array", "items": {"type": "string"}}
            }
          }
        },
        "total_recommendations": {"type": "integer"},
        "success": {"type": "boolean"}
      },
      "required": [
        "recommendation_summary",
        "recommended_jobs",
        "total_recommendations",
        "success"
      ]
    }
  # Field names must match the schema exactly for database persistence.

  agent: linkedin_recommendations_fetcher

compile_recommendations_report:
  description: >
    Compile a comprehensive LinkedIn recommendations report that organizes the fetched
    job recommendations into actionable insights for job candidates. Focus on explaining
    why jobs were recommended and providing clear next steps for each opportunity.
    This complements direct job searches with LinkedIn's algorithmic suggestions.

  expected_output: >
    JSON object matching schema:
    {
      "type": "object",
      "properties": {
        "executive_summary": {"type": "string"},
        "top_recommendations": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "rank": {"type": "integer"},
              "job_title": {"type": "string"},
              "company_name": {"type": "string"},
              "recommendation_rationale": {"type": "string"},
              "action_items": {"type": "array", "items": {"type": "string"}}
            }
          }
        },
        "recommendation_insights": {"type": "array", "items": {"type": "string"}},
        "profile_optimization_tips": {"type": "array", "items": {"type": "string"}}
      },
      "required": [
        "executive_summary",
        "top_recommendations",
        "recommendation_insights",
        "profile_optimization_tips"
      ]
    }
  # Field names must match the schema exactly.

  agent: linkedin_recommendations_reporter
  context: [fetch_recommended_jobs]