fetch_recommended_jobs:
  description: >
    Fetch personalized job recommendations from LinkedIn using the 'get_recommended_jobs' MCP tool.
    Parse and structure the raw data to populate the jobs database table. Focus on extracting
    all available data from the LinkedIn response and mapping it to the appropriate database fields.
    
    Key data extraction tasks:
    - Parse company field to extract company name, location, and salary info
    - Clean job titles (remove "with verification" text)
    - Extract location components (city, state) when possible
    - Determine if position is remote/hybrid/on-site from location text
    - Parse salary ranges into min/max amounts when available
    - Store complete raw response in source_raw field

  expected_output: >
    JSON array of job objects ready for database insertion with the following structure:
    [
      {
        "site": "linkedin",
        "job_url": "extracted_linkedin_url",
        "title": "cleaned_job_title", 
        "company": "extracted_company_name",
        "location_city": "parsed_city_or_null",
        "location_state": "parsed_state_or_null", 
        "location_country": "US_or_null",
        "is_remote": "boolean_based_on_location",
        "compensation": "salary_text_if_available",
        "min_amount": "numeric_min_salary_or_null",
        "max_amount": "numeric_max_salary_or_null",
        "currency": "USD_if_salary_present",
        "description": "job_description_if_available",
        "source_raw": "complete_original_linkedin_response_object"
      }
    ]
    
    Important: 
    - Return ONLY the JSON array, no additional text or formatting
    - Include source_raw field with complete original data from LinkedIn
    - Set site to "linkedin" for all records
    - Parse location strings like "Seattle, WA" into city/state components
    - Extract salary ranges like "$150K - $200K" into min_amount/max_amount
    - Set is_remote based on location containing "Remote" or "Hybrid"
    - Leave fields null if data is not available rather than making assumptions

  agent: linkedin_recommendations_fetcher